config/routes.rb
SwDrip::Application.routes.draw do

  root :to => 'user#dashboard'
  
  match 'register' => 'user#register', :via => [:GET,:POST], :as => 'user_register'
  
  resources :transactions, :as => 'trans', :controller => 'trans' do
    collection do
      get 'calendar' => 'trans#calendar'
      get 'calendar/events'   => 'trans#calendarevents'
      
    end
    
    
  end
  
  namespace :user do
    match '(/:action)', :via => [:GET]
    match 'login'     , :via => [:GET, :POST]
    match 'landing'   , :via => [:GET]
    match 'dashboard' , :via => [:GET]
    match 'profile'   , :via => [:GET]
    match 'logout'    , :via => [:POST]
    match 'change_pwd', :via => :put
  end
  
  resources :accounts do
    
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  validates_length_of :first_name, maximum: 50
  validates_length_of :last_name, maximum: 50
  validates_uniqueness_of :email
  validates_presence_of :email, :message => "email is required"
  validates_presence_of :password, :message => "password is required"
  validates_length_of :password, in: 5..20
  validates_format_of :email, :with => /\A.+@.+\z/, :message => "email format is not valid"
  validates_confirmation_of :password, :message => "password should match the confirmation"

  field :email, type: String
  field :password, type: String
  field :first_name, type: String
  field :last_name, type: String

  has_many :accounts

  after_create do
    acc = Cash.new(:name => "Cash in hand", :description => "Your cash here")
    accounts << acc
    self.save!
  end

  # # Adds account to this user. While doing so, it will call add_user! method
  # # of the account object being added to associate the user to that account
  def add_account(acc)
    if !accounts.find(acc.id)
      accounts << acc
      save!
    end
  end

  # # Removes the account association from this user
  def remove_account(acc)
    accounts.delete(acc)
    save!
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :require_user_login, :except => [:register, :landing, :login]
  layout 'user'
  
  def index
    redirect_to :user_dashboard
  end

  def dashboard
    @accounts = @user.accounts
    @new_transaction = Transaction.new()
  end

  def profile
    
  end
  
  # Change a user's password 
  def change_pwd
    @user = current_user?
    old_password = params[:old_password]
    new_password = params[:new_password]
    new_password_confirm = params[:confirm_password]
    
    respond_to do |f|      
      if is_valid?(@user.userid, old_password)
        @user.password = new_password
        
        if @user.save
          flash[:notice] = "Password changed successfully"
          f.html{ redirect_to user_profile_path }
        else
          flash[:error] = "Unable to change your password"
          f.html{ redirect_to user_profile_path }
        end
      else
        flash[:error] = "Unable to verify your existing password!"
        f.html{ redirect_to user_profile_path }
      end
    end
  end

  # display Registration page
  
  def register
    respond_to do |f|
      if request.post?        
        @user = User.new(params[:user])
        if @user.save
          current_user?(@user)
          f.html{ redirect_to user_landing_path }
        else
          flash[:error] = @user.errors.full_messages
          f.html{ render 'register', :layout => 'application', errors: @user.errors.full_messages }
        end
      else
        if current_user?
          flash[:error] = "Seems like you are already logged on, please logout first."
          f.html{ redirect_to user_dashboard_path }
        end
        
        @user = User.new()
        f.html{ render 'register', :layout => 'application' }
      end
    end
  end
  
  # the 1st page a successfully registered user enters
  def landing
    @user = current_user?
  end
  
  
  def login
    respond_to do |f|
      if request.post?
        email = params[:user][:email]
        passwd = params[:user][:password]
        kalive = (params["keep-alive"]  == "on")

        @user = is_valid?(email, passwd)
        
        if !@user.nil?
          current_user?(@user, kalive)
          f.html{ redirect_to user_dashboard_path }
        else
          flash[:error] = 'Wrong username or password.'
          f.html{ render 'login', :layout => 'application' }
        end
      else
        f.html{ render 'login', :layout => 'application' }
      end
    end
  end
  
  def logout
    session.delete :logined_user
    redirect_to root_path
  end
  
  
  def is_valid?(email, passwd)
    User.where(:email => email, :password => passwd).first
  end
    
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_login.haml
=f.text_field :email, :value => @email, :type=>"email", :class=>"form-control", :placeholder=>"Email address", :required => ""
=f.password_field :password, :class=>"form-control",:placeholder=>"Password", :required => ""
%label{:class=>"checkbox"}
  %input{:type=>"checkbox", :name=>"keep-alive"} Remember me

app/views/user/_new_transaction.haml
%div#add_trans
  / Nav tabs
  %ul{:class=>"nav nav-tabs"}
    %li{:class=>"active"}
      %a{ :href => '#tab-expenses', :data=>{:toggle=>"tab"} } Expenses
    %li
      %a{ :href => '#tab-income', :data=>{:toggle=>"tab"} } Income
  %div.tab-content
    %div{:id=>"tab-expenses",:class=>"tab-pane fade in panel panel-default active"}
      %div{:class=>"panel-body"}
        =form_for @new_transaction, :html=>{:class=>"form-inline", :role=>"form"}, :as => :tran, :url => trans_path, :validate => true do |f|    
          =render :partial => 'trans/form', :locals => { :f => f, :trans => Transaction.new, :op => '-' }
          %div.form-group
            %input{ :type => 'submit', :value => 'Submit', :class => 'btn' }
    %div#tab-income{:class=>"tab-pane fade panel panel-default"}
      %div{:class=>"panel-body"}
        =form_for @new_transaction, :html=>{:class=>"form-inline", :role=>"form"}, :as => :tran, :url => trans_path, :validate => true do |f|
          =render :partial => 'trans/form', :locals => { :f => f, :trans => Transaction.new, :op => '+' }
          %div.form-group
            %input{ :type => 'submit', :value => 'Submit', :class => 'btn' }
      

app/views/user/dashboard.haml
%h4 Dashboard
-@accounts.each do |a|
  %table#accounts{:class=>"table"}
    %thead
      %tr
        %th{ :colspan => 2, :style=> 'width:70%;' }
          =a.name
          =" (#{a.currency} #{account_type_display_name(a._type)})"
        %th{ :style=> 'width:15%;' }
          =("Initial balance <br />" + currencify(a.initial_balance)).html_safe
        %th{ :style=> 'width:15%;' }
    %tbody
      -a.transactions.sort(:created_at.desc).each do |t|
        %tr
          %td{:class=>"created_at"}=t.created_at
          %td=t.description
          %td.currency=currencify(t.amount, :show_operator => 1)
          %td.func{ :style => 'text-align: center;' }
            %button{:type=>"button",:class=>"btn btn-xs btn-default",:data=>{:js=>"modal-edit-transaction",:url=>"#{edit_tran_path(t._id)}",:target=>"#edit-trans",:id=>t._id}} edit
            =link_to 'delete', tran_path(t.id), {:class=>"btn btn-xs btn-danger", :confirm=>'Are you sure?', :method=>:delete}
    %tfoot
      %tr
        %td
        %td{ :style => 'text-align:right;' } Current balance: 
        %td
          =currencify(a.current_balance)
        %td

%div{:id=>"edit-trans",:class=>"modal fade",:tabindex=>"-1",:role=>"dialog",:aria=>{:labelledby=>"modal-title",:hidden=>"true"}}
  %div{:class=>"modal-dialog"}
    %div{:class=>"modal-content"}
      %div{:class=>"modal-header"}
        %button{:type=>"button",:class=>"close",:data=>{:dismiss=>"modal"}} x
        %h4{:class=>"modal-title",:id=>"modal-title"} Edit transaction
      %div{:class=>"modal-body"}

-content_for :js do
  :coffee
    $(document).ready ->
      $('#edit-trans, #add-trans').on 'shown.bs.modal', (e) ->
        $('.txt-amount').focus(->
          $(this).select()
        ).mouseup (e) ->
          e.preventDefault()

        $('.txt-amount', $('div.tab-pane.fade.active')).focus()

app/views/user/landing.haml
%h3 Thank you for registration!
%p 
  An email is sent to your email address: 
  %span{ :class => 'email' }
    =@user.email
  ,please follow the instruction in the email to activate your account.
  %br
  If you are having problem activating your account, please 
  %a{ :href=> '#'} request another email

app/views/user/login.haml
= content_for :css do
  = stylesheet_link_tag "login", :media => "all"

=form_for 'user', :html => {:role=>"form", :class=>"form-signin" }, :url => user_login_path, :validation => true do |f|
  %h3{:class=>"form-signin-heading"} Login
  =render 'login', :f => f
  %div{:class=>"col-sm-offset-2 col-sm-10"}
    or 
    =link_to 'register', user_register_path
    account for yourself.
  %input{ :type => 'submit', :class => 'btn btn-lg btn-primary btn-block', :value => 'login' }
  
  

app/views/user/profile.haml
%h3=@user.email
%p
  =form_tag 'update_profile', :method => :put do |f|
    %span{ :id => 'email' }
      %label
        =@user.email
      =text_field_tag 'email', @user.email, { :class => 'text_field hidden' }
      %a{ :href => '#', :id => 'edit_email' } edit
      %a{ :href => '#', :id => 'done_edit_email' } done

=form_tag 'change_pwd', :method => :put do |f|
  %fieldset
    %legend Change password
    %dl
      %dt
        %label Existing Pwd: 
      %dd=password_field_tag 'old_password'
    %dl
      %dt
        %label New Password: 
      %dd=password_field_tag 'new_password'
    %dl
      %dt
        %label Confirm:
      %dd=password_field_tag 'confirm_password'
    %input{ :type => 'submit', :class => 'submit', :value => 'change password' } 

app/views/user/register.haml
-content_for :css do
  %style{:type=>"text/css"}


%h3 Register an account

=form_for @user, :url => user_register_path, :validate => true, :html=>{:class=>"col-sm-6",:role=>"form"} do |f|
  %div.form-group
    =f.label :eamil, 'Email'
    =f.text_field :email, :value => @user.email, :class=>"form-control", :placeholder=>"Email"
  %div.form-group
    =f.label :password, 'Password'
    =f.password_field :password, :value => @user.password, :class=>"form-control", :placeholder=>"Password"
  %div.form-group
    =f.password_field :password_confirmation, :class=>"form-control", :placeholder=>"Confirm password"
  %div.form-group
    %input{ :type => 'submit', :value => 'Register', :class => 'btn btn-primary' }

  %p
    please
    =link_to 'login', user_login_path
    if you are already member of us