config/routes.rb
SwDrip::Application.routes.draw do

  root :to => 'user#dashboard'
  
  match 'register' => 'user#register', :via => [:GET,:POST], :as => 'user_register'
  
  resources :transactions, :as => 'trans', :controller => 'trans' do
    collection do
      get 'calendar' => 'trans#calendar'
      get 'calendar/events'   => 'trans#calendarevents'
      
    end
    
    
  end
  
  namespace :user do
    match '(/:action)', :via => [:GET]
    match 'login'     , :via => [:GET, :POST]
    match 'landing'   , :via => [:GET]
    match 'dashboard' , :via => [:GET]
    match 'profile'   , :via => [:GET]
    match 'logout'    , :via => [:POST]
    match 'change_pwd', :via => :put
  end
  
  resources :accounts do
    
  end

end

app/models/transaction.rb
# A transaction should belongs to one account, and belongs to one user
class Transaction
  include Mongoid::Document
  include Mongoid::Timestamps
  validates_numericality_of :amount, :message => "amount should be numerical"
  
  after_save :update_account_balance
  before_update :save_amount_before_update
  
  field :description, type: String, :default => ''
  field :amount, type: BigDecimal
  
  # Associations  
  belongs_to :account
  belongs_to :user
  
  # Class variables  
  @@original_amount=0
   
  # Queries the transaction table that is done by particular user
  
  def self.done_by(user)
    Transaction.where(:user_id => user.id)
  end  
  
    
  private
    
    # Perform this action after transaction bing updated
    def update_account_balance
      diff = self.amount
      if @@original_amount != 0 && @@original_amount != self.amount
        #
        # workout the difference between new and old amount
        @@original_amount -= self.amount
        if self.amount > @@original_amount
          diff = self.amount - @@original_amount
        else
          diff = @@original_amount - self.amount
        end
      end
      
      account.update_current_balance(diff)
    end

    
    # Saves the original amount before being replaced
    
    def save_amount_before_update
      @@original_amount = self.amount
    end
  
end

app/controllers/trans_controller.rb
class TransController < ApplicationController
  before_filter :require_user_login
  respond_to :json
  layout 'user'

  # Display a quick form to create transaction,
  # The page should take paramenter[:account] to have the account preselected in dropdown list
  def new
    @account = params[:account].nil? ? nil : Account.find(params[:account])
    @accounts = Account.owned_by(@user)
    @new_transaction = Transaction.new()

    respond_to do |f|
      f.html{ render :layout=>nil }
    end
  end
  
  # Creates a transaction record
  def create
    @trans = Transaction.new(params[:tran])
    @fromacc = Account.find(params[:account])
    
    # assume that input are all nutual numbers, we use operation param to 
    # determine the number
    amount = (params[:operation] == '-') ? -BigDecimal.new(@trans.amount) : BigDecimal.new(@trans.amount)
    @trans.amount = amount
    
    @trans.account = @fromacc
    @trans.user = @user
    
    respond_to do |f|
      if @trans.save!
        msg = "Transaction created"
        flash[:notice] = msg
        f.html{ redirect_to user_dashboard_path, :recent => @trans }
        f.json{ render json: { :status => :success, :message => msg, :detail => @trans.as_json } }
      else
        msg = "failed to create transaction"
        flash[:notice] = msg
        f.html{ render user_dashboard_path, :recent => @trans }
        f.json{ render json: {:status => :error, :message => msg } }
      end
    end
  end
  
  
  # Destroy a transaction record 
  def destroy
    @trans = Transaction.find(params[:id])
    
    respond_to do |f|
      if @trans.destroy
        flash[:notice] = 'Transaction deleted'
        f.html{ redirect_to user_dashboard_path }
      else
        flash[:notice] = 'Failed to delete transaction'
        f.html{ render user_dashboard_path, :recent => @trans }
      end
    end
  end
  
  # AKA Daily transactions
  def index
    @default_days = 7
    account_id = params[:account]
    begin
      @days = Integer(params[:days], 10)
    rescue
      @days = @default_days
    end
    
    tquery = Transaction.done_by(@user)
      .where(:created_at.gte => @days.days.ago)
    
    if(!account_id.nil?)
      tquery = tquery.where(:account_id => account_id)
    end
    
    @trans = tquery.sort(:created_at.desc)
    @total_expenses = @trans.collect{|m| m.amount }.inject{|sum, t| sum + t }
    @total_expenses = 0 if @total_expenses.nil?
  end
  
  
  # Shows a calendar view of the expenses
  def calendar
    today = params[:f] ? params[:f] : Time.now.utc.to_date
    @new_transaction = Transaction.new()
  end
  
  
  # Provide a json calendar events feed to be consumed by calendar
  def calendarevents
    operator = (params[:op] == '+') ? '+' : '-'
    start = params[:start] ? DateTime.strptime(params[:start],'%s') : DateTime.new(Date.today.year, Date.today.month, 1)
    to = params[:end] ? DateTime.strptime(params[:end], '%s') : DateTime.civil(Date.today.year, Date.today.month, -1)
    
    start = Time.utc(start.year, start.month, start.day)
    to = Time.utc(to.year, to.month, to.day)
    
    events = Transaction.done_by(@user).where(:created_at.gte => start).where(:created_at.lt => to)
    if(operator == '+')
      events = events.where(:amount.gte => 0)
    else
      events = events.where(:amount.lte => 0)
    end
    
    respond_to do |f|

      json = {
          :success => 1,
          :result => events.all.map!{|e| 
            {
              :id=>e._id.to_s,
              :title=>"#{e.description} [#{e.amount}]",
              :url=>url_for(:controller=>"trans",:action=>"show",:id=>e._id.to_s),
              :class=>(e.amount>=0) ? "event-info" : "event-warning",
              :start=>e.created_at.to_time.to_i*1000,
              :end=>(e.created_at.to_time.to_i+60)*1000
            }
          }
      }

      f.html{ render :json => json }
      f.json{ render :json => json }
    end

  end
  
  # reviewing single transaction
  def show
    @trans = Transaction.find(params[:id])

    respond_to do |f|
      if @trans.nil?
        flash[:error] = 'Failed to find the transaction to edit'
        f.html{ }
      else
        f.html{ render :layout=>"application" }
      end
    end
  end
  
  # trying to edit a transaction
  def edit
    @trans = Transaction.find(params[:id])
    
    respond_to do |f|
      if @trans.nil?
        flash[:error] = 'Failed to find the transaction to edit'
        f.html{ redirect_to user_dashboard_path }
      else
        f.html{ render :layout=>nil }
      end
    end
  end
  
  # Trying to update a transaction
  def update
    @trans = Transaction.find(params[:id])
    params[:tran][:amount] = (params[:operation] == '-') ? -(params[:tran][:amount].to_f) : params[:tran][:amount]
    
    respond_to do |f|
      if @trans.update_attributes(params[:tran])
        flash[:notice] = 'Transaction updated successfully'
        f.html{ redirect_to trans_path }
      else
        flash[:notice] = 'Failed to update transaction'
        f.html{ render edit_tran(@trans), :recent => @trans }
      end
    end
  end
  
  
end

app/helpers/trans_helper.rb
module TransHelper

  # Generates a dropdown selection list of, basically + and - signs for user to choose the kinda operation
  # of the given transaction 
  def h_trans_op_dropdown(amount, options={})
    op_4_select = options_for_select(['-', '+'], (amount.nil? || amount < 0) ? '-' : '+') 
    select_tag :operation, op_4_select, options
  end
  
end

app/views/trans/_form.haml
%div.form-group
  =f.label :amount, 'Amount', {:class=>"sr-only"}
  =h_action_dispatcher('edit') { h_trans_op_dropdown(trans.amount, {:class=>"form-control"}).html_safe }
  =h_action_dispatcher('new') { hidden_field_tag(:operation, op) }
%div.form-group
  =f.text_field :amount, {:class=>"form-control txt-amount", :size => '15', :value => trans.amount.nil? ? 0 : trans.amount.abs }
%div.form-group
  =h_account_selection(@accounts, {:class=>"form-control"})
%div.form-group
  =f.label :name, 'Description', {:class=>"sr-only"}
  =f.text_field :description, {:class=>"form-control", :placeholder=>"Description"}

=hidden_field_tag :operation, op

app/views/trans/calendar.haml
%h3 Calendar
        
/ -content_for :css do
/   =stylesheet_link_tag    "bootstrap-calendar/calendar"

%div{:id=>"calendar",:data=>{:event=>{:url=>"#{url_for calendar_events_trans_path}"}}}

%div{:id=>"events-modal",:class=>"modal fade",:role=>"dialog",:tabindex=>"-1",:aria=>{:labelledby=>"modal-label",:hidden=>"true"}}
  %div{:class=>"modal-dialog"}
    %div{:class=>"modal-content"}
      %div{:class=>"modal-body"}
      %div{:class=>"modal-footer"}
        %button{:type=>"button",:class=>"btn btn-default",:data=>{:dismiss=>"modal"}} close


%div#add_transaction{:style=>'display:absolute; top: 100px; left: 20px;'}
  =render 'user/new_transaction', :new_transaction => @new_transaction

app/views/trans/edit.haml
=form_for @trans, :as => :tran, :url => tran_path, :validate => true, :html => {:role=>"form", :class=>"form-inline" } do |f|
  =render :partial => 'form', :locals => {:f => f, :trans => @trans, :op => ( (@trans.amount >= 0) ? '+' : '-' ) }
  %div{:class=>"form-group"}
    %input{ :type=>'submit', :value=>'submit', :class => 'btn' }
  %input{:type=>"hidden",:name=>""}

app/views/trans/index.haml
%h3 Transactions
%h5
  Showing recent 
  %strong.dayrange=@days
  days of transactions
  of Total expenses/income: 
  %strong=currencify(@total_expenses)

%table.table
  %thead
    %tr
      %th Time
      %th Description
      %th Amount
      %th Account
      %th
    -@trans.each do |key, val|
      %tr
        %td.day_column{:rowspan=>val.count+1}=datefy(val.first.created_at)
      -val.each do |v|
        %tr
          %td=v.description
          %td=currencify(v.amount)
          %td=v.account.name
          %td.func
            =link_to 'edit', edit_tran_path(v._id)
            =link_to 'delete', tran_path(v.id), :confirm => 'Are you sure?', :method => :delete
  / -@trans.group_by{|gg| gg.created_at.day }.each do |key,val|
  /   %tr
  /     %td.day_column{:rowspan=>val.count+1}=datefy(val.first.created_at)
  /   -val.each do |v|
  /     %tr
  /       %td=v.description
  /       %td=currencify(v.amount)
  /       %td=v.account.name
  /       %td.func
  /         =link_to 'edit', edit_tran_path(v._id)
  /         =link_to 'delete', tran_path(v.id), :confirm => 'Are you sure?', :method => :delete
%div
  %div=link_to "see more &raquo;".html_safe, trans_path(:days => @days+@default_days)

app/views/trans/new.haml
%ul{:id=>"operation_tabs",:class=>"nav nav-tabs"}
  %li
    %a{ :href => '#tab-expenses',:data=>{:toggle=>"tab"} } Expenses
  %li
    %a{ :href => '#tab-income',:data=>{:toggle=>"tab"} } Income
%div{:class=>"tab-content"}
  %div{:id=>"tab-expenses",:class=>"tab-pane fade in active"}
    =form_for @new_transaction, :as => :tran, :url => trans_path, :validate => true, :html=>{:id=>"new-expense", :class=>"form-inline"} do |f|
      %br/
      =render :partial => 'trans/form', :locals => { :f => f, :trans => Transaction.new, :op => '-' }
      %div{:class=>"form-group"}
        %input{ :type => 'submit', :value =>'Submit', :class=>'btn btn-default' }
  %div{:id=>"tab-income",:class=>"tab-pane fade"}
    =form_for @new_transaction, :as => :tran, :url => trans_path, :validate => true, :html=>{:id=>"new-income", :class=>"form-inline"} do |f|
      %br/
      =render :partial => 'trans/form', :locals => { :f => f, :trans => Transaction.new, :op => '+' }
      %div{:class=>"form-group"}
        %input{ :type => 'submit', :value => 'Submit', :class => 'btn btn-default' }

:coffee
  $ ->
    $('#operation_tabs a:first').tab('show')
    
    $("#new-expense, #new-income").submit ->
      valueToSubmit = $(this).serialize()

      $.ajax
        url: $(this).attr("action")
        data: valueToSubmit
        method: "POST"
        dataType: "JSON"
        success: (resp)->
          if(resp.status == "success")
            $("data-js['modal-add-transaction']").modal('hide')
          else
            console.log("popup error")
          console.log(resp)          

      console.log valueToSubmit

      return false

app/views/trans/show.haml
%h5=@trans.description
%div
  %em=@trans.created_at
  