config/routes.rb
SwDrip::Application.routes.draw do

  root :to => 'user#dashboard'
  
  match 'register' => 'user#register', :via => [:GET,:POST], :as => 'user_register'
  
  resources :transactions, :as => 'trans', :controller => 'trans' do
    collection do
      get 'calendar' => 'trans#calendar'
      get 'calendar/events'   => 'trans#calendarevents'
      
    end
    
    
  end
  
  namespace :user do
    match '(/:action)', :via => [:GET]
    match 'login'     , :via => [:GET, :POST]
    match 'landing'   , :via => [:GET]
    match 'dashboard' , :via => [:GET]
    match 'profile'   , :via => [:GET]
    match 'logout'    , :via => [:POST]
    match 'change_pwd', :via => :put
  end
  
  resources :accounts do
    
  end

end

app/views/layouts/__application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwDrip</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.haml
!!! 1.1
%html
  %head
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    %title Signin
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    params[:controller]
    = content_for?(:css) ? yield(:css) : ''
    = csrf_meta_tags
  %body
    %div{:class=>"container"}
      -if flash[:error] 
        %div.alert.alert-danger=flash[:error]
      -if flash[:notice]
        %div.alert.alert-warning=flash[:notice]
      
      = yield
    
    = javascript_include_tag "application"
    =# javascript_include_tag "rails.validations"
    =# javascript_include_tag "rails.validations.custom"
    = javascript_include_tag params[:controller]
    = content_for?(:js) ? yield(:js) : ''

app/views/layouts/user.haml
!!! 1.1
%html
  %head
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    %title User Drip!
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    params[:controller]
    %style{:type=>"text/css"}
      -# http://stackoverflow.com/questions/10336194/twitter-bootstrap-top-nav-bar-blocking-top-content-of-the-page
      body { padding-top: 60px; }
      @media (max-width: 979px) { body { padding-top: 0px; } }
    = content_for?(:css) ? yield(:css) : ''
    
    -# 
      HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries 
      WARNING: Respond.js doesn't work if you view the page via file:// -->
    /[if lt IE 9]
      %script{ :src => "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{ :src => "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}

    = csrf_meta_tags
    
  %body
    %div{ :class => "navbar navbar-inverse navbar-fixed-top", :role=>"navigation" }
      %div{ :class => "container" }
        %div{ :class => "navbar-header" }
          %a{ :class => "navbar-brand", :href=>"#"} Drip
        %div{ :class => "navbar-collapse collapse" }
          %ul{ :class => "nav navbar-nav" }
            %li{ :class => "active" }
              =link_to 'Home', user_dashboard_path
            %li{ :class => "#daily-transactions" }
              =link_to 'Daily transactions', trans_path
            %li{ :class=>"dropdown" } 
              %a{ :href=>"#", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"}} 
                Manage Accounts
                %b{:class=>"caret"}
              %ul{:class=>"dropdown-menu"}
                %li=link_to 'New Account', new_account_path
                %li{:class=>"divider"}
                %li{:class=>"dropdown-submenu"}
                  %a{:href=>"#",:tabindex=>"-1"} My Accounts
                  %ul{:class=>"dropdown-menu"}
                    -@my_accounts.each do |a|
                      %li=link_to a.name, account_path(a)
                
          %div{:class=>"navbar-right"}
            %div.user
              &raquo; Welcome
              =link_to @user.email, user_profile_path
              \. 
              =link_to 'logout', user_logout_path

    %div{:class=>"container"}
      %div{:class=>"row"}
        %div{:class=>"col-md-2"}
          %ul{:class=>"nav nav-pills nav-stacked"}
            %li{:class => "#{current_item?(@current_action, "active")}"}
              =link_to "Dashboard", user_dashboard_path 
            %li{:class => "#{current_item?(@current_action, "active")}"}
              =link_to "Account Summary", accounts_path
            %li{:class => "#{current_item?(@current_action, "active")}"}
              =link_to "Calendar", calendar_trans_path
            %li{:class => "#{current_item?(@current_action, "active")}"}
              =link_to "Account Summary", "#", { :class => "dashboard" }
        %div{:class=>"col-md-10"}
          -if flash[:error] 
            %div.alert.alert-danger=flash[:error]
          -if flash[:notice]
            %div.alert.alert-warning=flash[:notice]
          
          %div
            %button{:type=>"button",:class=>"btn btn-xs btn-default",:data=>{:js=>"modal-add-transaction",:url=>"#{new_tran_path()}",:target=>"#add-trans"}} add expenses
          = yield


      %div{:id=>"add-trans",:class=>"modal fade",:tabindex=>"-1",:role=>"dialog",:aria=>{:labelledby=>"modal-title",:hidden=>"true"}}
        %div{:class=>"modal-dialog"}
          %div{:class=>"modal-content"}
            %div{:class=>"modal-header"}
              %button{:type=>"button",:class=>"close",:data=>{:dismiss=>"modal"}} x
              %h4{:class=>"modal-title",:id=>"modal-title"} New transaction
            %div{:class=>"modal-body"}

    =# javascript_include_tag "https://code.jquery.com/jquery.js"
    = javascript_include_tag "application"
    = javascript_include_tag params[:controller]
    = content_for?(:js) ? yield(:js) : ''