config/routes.rb
SwDrip::Application.routes.draw do

  root :to => 'user#dashboard'
  
  match 'register' => 'user#register', :via => [:GET,:POST], :as => 'user_register'
  
  resources :transactions, :as => 'trans', :controller => 'trans' do
    collection do
      get 'calendar' => 'trans#calendar'
      get 'calendar/events'   => 'trans#calendarevents'
      
    end
    
    
  end
  
  namespace :user do
    match '(/:action)', :via => [:GET]
    match 'login'     , :via => [:GET, :POST]
    match 'landing'   , :via => [:GET]
    match 'dashboard' , :via => [:GET]
    match 'profile'   , :via => [:GET]
    match 'logout'    , :via => [:POST]
    match 'change_pwd', :via => :put
  end
  
  resources :accounts do
    
  end

end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  validates_presence_of :name, :message => "account name is required."
  validates_length_of :name, in: 5..50

  field :name, type: String
  field :number, type: String
  field :description, type: String
  field :initial_balance, type: BigDecimal, :default => 0.0
  field :current_balance, type: BigDecimal, :default => 0.0

  field :interest, type: BigDecimal, :default => 0.0
  field :currency, type: String
  
  belongs_to :user

  attr_accessor :_type

  before_create do
    self.current_balance = initial_balance
  end

  def transactions
    Transaction.where(:account_id => self.id)
  end

  def update_current_balance(amount)
    self.current_balance += amount
    self.save!
  end

  
  def self.owned_by(user)
    Account.where(:user_id => user.id)
  end

  # def change_type(new_type)
  #   db = Mongoid::Sessions.default
  #   hs = Hash[self.attributes]
  #   hs['_type'] = new_type

  #   puts hs.inspect

  #   #db[:accounts].find(_id: self.id).update(hs)
  # end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_user_login
  layout 'user'

  def index
    @accounts = @user.accounts
  end

  def new
    @account = Account.new()
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    
    respond_to do |f|
      if @account.update_attributes(params[:account])
        flash[:notice] = "Account updated successfully"
        f.html{ redirect_to accounts_path(), :recent => @account  }
      else
        flash[:error] = "Failed to update account"
        f.html{ render 'edit' }
      end
    end
  end
  
  def destroy
    @account = Account.find(params[:id])
    respond_to do |f|
      if @account.destroy
        flash[:notice] = 'Account deleted successfully'
      else
        flash[:error] = "Was unable to delete the specified account"
      end
      f.html{ redirect_to accounts_path, :recent => @account }
    end
  end
  
  
  def create
    if params[:account][:_type] == 'SavingsAccount'
      @account = SavingsAccount.new(params[:account])
    elsif params[:account][:_type] == 'TermDepositAccount'
      @account = TermDepositAccount.new(params[:account])
    elsif params[:account][:_type] == 'Cash'
      @account = Cash.new(params[:account])
    end

    respond_to do |f|
      if @account.save
        @user.add_account(@account)
        flash[:notice] = "Account created successfully"
        f.html{ redirect_to accounts_path, :recent => @account }
      else
        flash[:error] = @account.errors.full_messages
        f.html{ render 'new' }
      end
    end
  end
  
  def show
    @account = Account.find(params[:id]) || err_notfound
  end
  

end

app/helpers/accounts_helper.rb
module AccountsHelper
  
  # Produce a drop down selection control to search for accounts
  def h_account_selection(accounts, options={})
    return accounts if accounts.nil?
    arr = []
    accounts.each do |a|
      arr << ["#{a.name} (#{a._type})", a._id]
    end
    select_tag :account, options_for_select(arr), options
  end
  
  # Produce a select_tag html element for account type
  def h_account_type_selection(form, obj, options={})
    selected_string = (obj._type.nil? ? "" : obj._type).gsub(/\s+/, '').strip
    
    form.select :_type,
      options_for_select(Settings.account_types.sort, selected_string), 
      {},
      options
  end
  
  # get account transaction
  
  def account_trans(account)
    return nil if account.nil?
    Transaction.where(:account => account)
  end
  
  # display friendly account type name by giving the shortened
  def h_account_type_name_by_index(index)
    Settings.account_types.each{ |a|
      return a[0] if a[1] == index
    }
  end
  
  # Sum each account balances
  
  def account_balance_sum(accounts)
    sum = 0
    accounts.each{|a| sum += a.current_balance }
    sum
  end
  
  
  ##
  ## Page view related helper methods
  ##
  

  
end

app/views/accounts/_form.haml
%div{:class=>"form-group"}
  =f.label :name, 'Account Name', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-5"}
    =f.text_field :name, {:class=>"form-control",:placeholder=>"name",:value => @account.name}

%div{:class=>"form-group"}
  =f.label :number, 'Account #', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-5"}
    =f.text_field :number, {:class=>"form-control",:placeholder=>"name",:value => @account.number}

%div{:class=>"form-group"}
  =f.label :description, 'Description', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-6"}
    =f.text_field :description, {:class=>"form-control",:placeholder=>"name",:value => @account.description}

%div{:class=>"form-group"}
  =f.label :initial_balance, 'Initial balance', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-4"}
    =f.text_field :initial_balance, {:class=>"form-control",:placeholder=>"name",:value => @account.initial_balance}

%div{:class=>"form-group"}
  =f.label 'account type', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-3"}
    =h_account_type_selection(f, @account, {:class=>"form-control"})

%div{:class=>"form-group"}
  =f.label :currency, 'Currency', {:class=>"col-sm-2 control-label"}
  %div{:class=>"col-sm-3"}
    =select(:account, :currency, options_for_select(Settings.currency, @account.currency), {}, :class=>"form-control col-sm-2")
  

app/views/accounts/edit.haml
%h3 Edit Account

=form_for @account, :as => :account, :url => account_path, :validate => true, :html=>{:class=>"form-horizontal", :role=>"form"} do |f|
  =render 'form', :f => f, :account => @account
  %div{:class=>"form-group"}
    %div{:class=>"col-sm-2"}
    %div{:class=>"col-sm-10"}
      %input{ :type=>'submit', :value=>'submit', :class => 'btn btn-primary' }

app/views/accounts/index.haml
%h3 Account Summary

%table{:class=>"table table-striped table-hover"}
  %thead
    %tr
      %th.name Account name
      %th #
      %th init. balance
      %th Current balance
      %th type
      %th 
  %tbody
  -@accounts.each do |a|
    %tr
      %td.name=a.name
      %td=a.number
      %td.currency
        =currencify(a.initial_balance, :currency_name => a.currency)
      %td.currency
        =currencify(a.current_balance, :currency_name => a.currency)
      %td
        =h_account_type_name_by_index(a._type)
      %td{:class=>"center-block"}
        =link_to 'edit', edit_account_path(a._id), {:class=>"btn btn-default btn-xs"}
        =link_to 'delete', account_path(a._id), {:class=>"btn btn-default btn-xs", :confirm => "Are you sure?", :method => :delete}
        =link_to '+', new_tran_path(:account => a), {:class => 'btn btn-default btn-xs btn-success'}
        =link_to 'transactions', trans_path(:account => a), { :class => 'btn btn-default btn-xs' }
  %tfoot
    %tr
      %td.func
        =link_to 'new account', new_account_path, { :class => 'button' }
      %td
      %td
      %td.currency
        Account balance: 
        =currencify(account_balance_sum(@accounts))
      %td
      %td

app/views/accounts/new.haml
%h3 New Account
%p You can create an
=form_for @account, :url => accounts_path, :validate => true, :html=>{:role=>"form",:class=>"form-horizontal"} do |f|
  =render 'form', :f=>f, :account => @account
  %div.form-group
    %div{:class=>"col-sm-2"}
    %div{:class=>"col-sm-10"}
      %input{ :value => 'submit', :type => 'submit', :class => 'btn btn-primary' }
    